config/routes.rb
HappyGeocode::Application.routes.draw do
  match 'map' => 'maps#index'
  match 'api_docs' => 'api_docs#index'

  root :to => 'welcome#about'

  namespace :api do
    resource :geocodes, defaults: { format: :json }
  end
end

app/models/city.rb
class City
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :name, String
  attribute :country_ref
  attribute :state_ref
  attribute :center
  attribute :radius

  def City.find_by_name(name)
    self.by_example name_normalized: name
  end

  def to_s
    "<#City name='#{name}'>"
  end
end

app/models/country.rb
class Country
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :name, String
  attribute :name_normalized, String
  attribute :center
  attribute :radius
end

app/models/request.rb
class Request
  include Ashikawa::AR::Model

  attribute :response
end

app/models/state.rb
class State
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :name, String
  attribute :name_normalized, String
  attribute :country_ref
  attribute :center
  attribute :radius
end

app/models/street.rb
class Street
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :name, String
  attribute :name_normalized, String
  attribute :city_ref
  attribute :zip_ref
  attribute :other_part_refs
  attribute :street

  attr_accessor :city_name
  attr_accessor :zip

  def Street.find_by_name(name)
    self.find_by_aql "FOR street IN streets FILTER street.name_normalized == '#{name}' RETURN street"
  end

  def Street.find(params)
    if params.has_key? :zip
      zip = Zip.find_by_name(params[:zip]).first
      lat = zip.center["lat"]
      lon = zip.center["lon"]
      radius = zip.radius
    elsif params.has_key? :city
      city = City.find_by_name(params[:city]).first
      lat = city.center["lat"]
      lon = city.center["lon"]
      radius = city.radius
    else
      return Street.find_by_name params[:street]
    end

    osm_ids = Ashikawa::AR::Setup.databases[:default].query "for street in streets filter street.name_normalized == '#{params[:street]}' return { osm_id: street.osm_id }"
    osm_ids = osm_ids.map { |raw| raw["osm_id"] }

    street_subquery = "[" + osm_ids.join(", ") + "]"

    query = "for street_point in within(street_points, #{lat}, #{lon}, #{radius}) " +
            "filter street_point.street_ref in #{street_subquery} " +
            "return street_point"

    street_points = StreetPoint.find_by_aql query

    street = Street.first_example osm_id: street_points.sample.street_ref

    street.city_name = city.name if city

    if zip
      street.zip = zip.name
      street.city_name = zip.city
    end

    [street]
  end

  def street_points
    StreetPoint.by_example street_ref: osm_id
  end

  def to_s
    "<#Street name='#{name}'>"
  end
end

app/models/street_point.rb
class StreetPoint
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :street_ref
  attribute :lat
  attribute :lon
end

app/models/zip.rb
class Zip
  include Ashikawa::AR::Model

  attribute :osm_id
  attribute :name, String
  attribute :name_normalized, String
  attribute :center
  attribute :radius
  attribute :state_ref
  attribute :country_ref
  attribute :city

  def Zip.find_by_name(name)
    self.by_example name: name
  end
end

app/controllers/api/geocodes_controller.rb
# encoding: utf-8
require 'geocoder'
module Api
  class GeocodesController < ApplicationController
    respond_to :json, :xml

    def show
      respond_with Geocoder.new.find(params)
    end

  end
end

app/controllers/api_docs_controller.rb
class ApiDocsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def about
    @team_members = [
      {
        name: "bitboxer",
        github: "https://github.com/bitboxer",
        twitter: "http://twitter.com/bitboxer",
        desc: %q{Owns a colorful collection of crayons},
        img: 'bitboxer.jpg'
      },
      {
        name: "klaustopher",
        github: "https://github.com/klaustopher",
        twitter: "http://twitter.com/klaustopher",
        desc: %q{Chocolate for the mob},
        img: 'klaustopher.jpg'
      },
      {
        name: "moonglum",
        github: "https://github.com/moonglum",
        twitter: "http://twitter.com/moonbeamlabs",
        desc: %q{Exchanged his hair for <3},
        img: 'moonglum.jpg'
      },
      {
        name: "EinLama",
        github: "https://github.com/EinLama",
        twitter: "http://twitter.com/l_ama",
        desc: %q{That mustache is real!},
        img: 'EinLama.jpg'
      }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def happy_face
    %w/:) :D :] ;) ;D L:D ^^/.sample
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/api_docs/index.html.haml
%h1.page-header.happy-caption API documentation

%h2.happy-caption Search for an address

:markdown
  Simply send a address to the geocoder with the string as **query** parameter:

.code= CodeRay.scan("http://happy-geoco.de/api/geocodes?query=Bruesseler%20Strasse%2055,%2050672%20Koeln", :html).div.html_safe

:markdown
  The result will be an array list of geocoded addresses. Each address has a qualifier that
  explains the quality of the match.

.code= CodeRay.scan("[{\n  \"street_name\": \"Bruesseler Strasse\",\n  \"street_number\": \"55\",\n  \"zip\": \"50672\",\n  \"city\": \"Köln\",\n  \"state\": \"NRW\",\n  \"country\": \"Germany\",\n  \"lat\": 50.937966,\n  \"lon\": 6.934578,\n  \"accuracy\": \"exact\",\n  \"accuracy_face\": \":D\"\n}]", :json).div.html_safe

:markdown
  Most of the fields are self explanitory. If the match is not exact, the result array will contain several entries.

  The **accuray** field is a hint about the quality of the geocoordinates. Possible values are:

%table.accuracy_explained.table.table-striped
  %thead
    %tr
      %th.accuracy_value
        Value
      %th
        Meaning
      %th.accurracy_happyface
        Accurracy face
  %tbody
    %tr
      %td.code_column
        exact
      %td
        Perfect match for the address
      %td.code_column
        \:D
    %tr
      %td.code_column
        street
      %td
        The street could be found, but we didn't find a match for the street number
      %td.code_column
        \:)
    %tr
      %td.code_column
        city
      %td
        We didn't find the street and give you the center of the city as a result
      %td.code_column
        \:O
    %tr
      %td.code_column
        zip
      %td
        We didn't find the street, but we have the center of that zip code area and give it to you instead
      %td.code_column
        \:/
    %tr
      %td.code_column
        wild_guess
      %td
        Okay, we found something, but this is most likely wrong
      %td.code_column
        \:(

%p
  Please mind the accuracy_face field - it displays the accuracy level in a not-boring way
  = happy_face

app/views/layouts/_navigation.html.haml
.navbar.happy-navbar
  .navbar-inner
    = link_to "Happy Geocode #{happy_face}", root_path, class: 'brand happy-caption'
    = render_navigation
    %form#mapSearch.navbar-form.form-search.pull-right{ method: 'get', action: map_path }
      #mapTooltip
        .close{style: "color: white; position: relative; top: -10px"} x
        %h4 Search for an address in NRW, Germany here
        %p
          Just search for a location. See the
          = link_to 'example', '/#example', color: '#fff'
          if you need help.
      .input-append
        %input.search-query{ type: 'text', name: 'query', value: params[:query] }
        %button.btn.js-mapsearch
          %i.icon-search

app/views/layouts/_rumble_warning.html.haml
.happy-notice.happy-rumble-warning.alert.alert-warning{ style: 'text-align: center; display: none;' }
  = link_to "x", "#", class: 'close', data: { dismiss: 'alert' }, title: 'Dismiss'

  This project was started as a
  = link_to "Rails Rumble 2012", 'http://railsrumble.com'
  project. If you like it, please consider
  = link_to "voting for us.", 'http://railsrumble.com/entries/210-happy-geocode'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Happy Geocode :D
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    :javascript
      var _gaq = _gaq || [];

      _gaq.push(['_setAccount', '#{request.domain == "railsrumble.com" ? 'UA-35565702-2' : 'UA-35565702-1'}']);
      _gaq.push(['_setDomainName', '#{request.domain == "railsrumble.com" ? 'r12.railsrumble.com' : 'happy-geoco.de'}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

%body
  .container
    = render partial: 'layouts/navigation'

    .happy-container
      - unless active_navigation_item_key == :map
        = render partial: 'layouts/rumble_warning'
      = yield

    %footer.happy-footer.muted
      %p
        This project was built in 48 hours for the
        = link_to "Rails Rumble 2012.", "http://railsrumble.com", target: '_blank'
        Makes use of
        = link_to "Font Awesome.", "http://fortawesome.github.com/Font-Awesome"

app/views/maps/index.html.haml
.happy-notice.alert.alert-error
  = link_to "x", "#", class: 'close', data: { dismiss: 'alert' }, title: 'Dismiss'
  %h4 Rumble Notice!
  %p
    The map only works with geodata from <strong>Northrhine Westfalia, Germany</strong>.
    %br
    Moar areas may follow. Since Openstreetmap provides a massive amount of data, we cannot add our whole planet at once.
    = happy_face

.happy-map.fullscreen
  #happyMap

app/views/welcome/_api.html.haml
.span3.about-item.thumbnail
  = image_tag 'api.jpg', class: 'img-rounded thumb'
  .caption
    .happy-content
      %h4.happy-caption
        Use our API
      %p
        You do not need a map or want to roll your own?
        No problem, simply use our API and work with raw
        data such as lat/lng.
      %p
        It is like &ndash; <strong>uber</strong> fast.<sup>1</sup>
      %p
        Our backend is based on
        = link_to 'ArangoDB', 'http://arangodb.org', target: '_blank'
        &ndash; a NoSQL database with native geo indices.

    = link_to api_docs_path, class: 'btn btn-info' do
      %i.icon-wrench
      Visit docs

app/views/welcome/_map.html.haml
.span3.about-item.thumbnail
  = image_tag 'map_shot.jpg', class: 'img-rounded thumb'
  .caption
    .happy-content
      %h4.happy-caption
        Watch on map
      %p
        Directly<sup>1</sup>
        see the results of your query on a sweet map.
      %p
        Quickly find your way around. Our maps and geo-data are made
        possible by the great
        = link_to 'Openstreetmap project.', 'http://openstreetmap.org', target: '_blank'
      %p
        Some day we might replace Google maps.<sup>1</sup>

    = link_to map_path, class: 'btn btn-info' do
      %i.icon-map-marker
      Visit map

app/views/welcome/_search.html.haml
.span3.offset1.about-item.thumbnail
  = image_tag 'street.jpg', class: 'img-rounded thumb'
  .caption
    %h4.happy-caption
      Search streets
    %p
      Enter an address
      %strike or landmark
      you wish to search for
      and be amazed by the awesome correct results you get back.<sup>1</sup>
    %p
      Happy geocode is always right and never fails.<sup>1</sup>
    %p
      If you are not an Earthling, be not afraid. We will eventually
      add support for your galaxy, too.<sup>1</sup>

app/views/welcome/about.html.haml
%section#aboutHappy
  %h1.page-header.happy-caption.happy-title
    = "Happy Geocode #{happy_face}"
    %small Openstreetmap geocoding done right

  .happy-map-logo

  .happy-about
    .row
      .happy-about-boxes
        = render partial: 'welcome/search'
        = render partial: 'welcome/map'
        = render partial: 'welcome/api'

    %small.muted.happy-lie
      1: Our manager claims so. Please do not sue us for false statements he made.
      He is currently out of office for a time travel and will return last year.

%section#example
  %h1.happy-caption Example
  %p
    Give us an address and we give you all the geo data
    = happy_face
  .happy-example
    .happy-input.pull-left
      %strong.desc Search string:
      .code= CodeRay.scan("'Bruesseler Strasse 55, 50672 Koeln'", :javascript).div.html_safe
    .happy-io.pull-left
      \=>
    .happy-output.pull-left
      %strong.desc Output:
      .code= CodeRay.scan("{\n  street_name: 'Bruesseler Strasse',\n  street_number: '55',\n  zip: '50672',\n  city: 'Koeln', state: 'NRW',\n  country: 'Germany',\n  lat: '50.937993', lng: '6.934578'\n}", :javascript).div.html_safe
    = link_to "#{map_path}?query=Bruesseler Strasse 55, 50672 Koeln",
        class: 'btn btn-success perform-example pull-left' do
      Run
      %i.icon-play


%section#supporters
  %h1.happy-caption
    Noble supporters
    %small thank you guys

  %ul.supporters-list
    %li
      %strong Office, power supply, pizza and beverages by
      %br
      = link_to 'http://en.triagens.com/', target: '_blank', class: 'supporter-image' do
        = image_tag 'triagens.png', title: 'triAGENS GmbH'
    %li
      %strong Powered by
      %br
      = link_to 'http://www.arangodb.org/', target: '_blank', class: 'supporter-image' do
        = image_tag 'arangodb.png', title: 'ArangoDB'
      = link_to 'http://www.openstreetmap.org/', target: '_blank', class: 'supporter-image' do
        = image_tag 'openstreetmap.png', title: 'OpenStreetMap'
      = link_to 'http://rubyonrails.org/', target: '_blank', class: 'supporter-image' do
        = image_tag 'rails.png', title: 'Ruby on Rails'

%section#team
  %h1.happy-caption The team

  %p
    Meet the humble folks behind this piece of software:

  .row-fluid
    %ul.thumbnails
      - @team_members.each do |hero|
        %li.span3
          .thumbnail
            = image_tag hero[:img], class: 'img-rounded'
            .caption.happy-team-member
              .vita
                %h4.happy-caption= hero[:name]
                %p= hero[:desc]
              = link_to hero[:github],
                  title: 'visit profile',
                  target: '_blank',
                  class: 'team-link pull-left' do
                %i.icon-github
                Github
              = link_to hero[:twitter],
                  title: 'visit profile',
                  target: '_blank',
                  class: 'team-link pull-right' do
                Twitter
                %i.icon-twitter

app/views/welcome/index.html.haml
.page-header
  %h1.happy-caption
    Welcome
    %small to the world of happy geocoding

%p
  This is a geo-service for querying streets, house numbers, zip codes, and other stuff. For implementation details please see our
  = link_to "About section.", about_path
%p
  The current implementation is restricted to the area around Cologne, Germany. Other locations will follow.

.happy-map-controls
  %form.form-search
    %input.input-medium.search-query{ type: 'text' }
    %button.btn
      %i.icon-search
      Search

.happy-map
  = image_tag 'http://placehold.it/900x450'